In [1]:
import requests
import requests_html
from requests_html import HTMLSession
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io

In [2]:
url = f"https://www.prizeinfo.net/all-prize-bond-first-second-record/"
session = HTMLSession()
response = session.get(url)
soup = bs(response.html.html, 'html.parser')

In [3]:
table = soup.find('table', attrs={'class':'table'})

In [4]:
data = pd.read_html(str(table))

In [5]:
dfs = pd.concat(data)

In [6]:
dfs.head(50)

,Prize Bond,Draw No.,1st,2nd,2nd.1,2nd.2,2nd.3,2nd.4,City,Date,Full List
0,Rs. 750,91,722561,321896,828159,873486,NaN,NaN,Lahore,15-07-2022,View
1,Rs. 200,90,489317,482044,585014,678913,720703.0,770704.0,Multan,15-06-2022,View
2,Rs. 25000 Premium,6,415455857641,127995,464283,482643,484175.0,585235.0,Hyderabad,10-06-2022,View
3,Rs. 40000 Premium,21,763153,16018,318363,341290,NaN,NaN,Muzaffarabad,10-06-2022,View
4,Rs. 100,38,93241,109857,297539,479884,NaN,NaN,Faisalabad,16-05-2022,View
5,Rs. 1500,90,928756,68381,673933,924554,NaN,NaN,Rawalpindi,16-05-2022,View
6,Rs. 750,90,394635,207865,529894,829039,NaN,NaN,Karachi,15-04-2022,View
7,Rs. 200,89,793039,128737,390413,591489,705889.0,796069.0,Lahore,15-03-2022,View
8,Rs. 40000 Premium,20,755505,216179,311017,335736,NaN,NaN,Quetta,10-03-2022,View
9,Rs. 25000 Premium,5,96298193729,66227,284279,604401,696721.0,901103.0,Rawalpindi,10-03-2022,View
10,Rs. 100,37,904546,74566,259751,885455,NaN,NaN,Hyderabad,15-02-2022,View
11,Rs. 1500,89,878598,243545,457662,509633,NaN,NaN,Muzaffarabad,15-02-2022,View
12,Rs. 750,89,4208,511294,549996,983274,NaN,NaN,Peshawar,17-01-2022,View
13,Rs. 200,88,259580,380,233133,725485,871732.0,956938.0,Hyderabad,15-12-2021,View
14,Rs. 40000 Premium,19,953829,366951,599135,629631,NaN,NaN,Lahore,10-12-2021,View
15,Rs. 25000 Premium,4,16253067408,38203,171265,551833,655804.0,916353.0,Quetta,10-12-2021,View
16,Rs. 100,36,406160,50000,422885,619067,NaN,NaN,Peshawar,15-11-2021,View
17,Rs. 1500,88,708623,121234,251386,788311,NaN,NaN,Faisalabad,15-11-2021,View
18,Rs. 750,88,69845,172166,321134,828622,NaN,NaN,Rawalpindi,15-10-2021,View
19,Rs. 200,87,752824,368787,412125,437022,490233.0,759209.0,Muzaffarabad,15-09-2021,View
20,Rs. 25000 Premium,3,77928879917,17928,299043,366072,435276.0,924342.0,Hyderabad,10-09-2021,View
21,Rs. 40000 Premium,18,619284,11192,82571,460593,NaN,NaN,Peshawar,10-09-2021,View
22,Rs. 100,35,891043,212399,288254,660539,NaN,NaN,Faisalabad,16-08-2021,View
23,Rs. 1500,87,581729,91829,210953,759528,NaN,NaN,Multan,16-08-2021,View
24,Rs. 750,87,331809,232705,842723,908062,NaN,NaN,Lahore,15-07-2021,View
25,Rs. 200,86,514859,129441,268617,317693,423265.0,914859.0,Peshawar,15-06-2021,View
26,Rs. 25000 Premium,2,171790639589,100688,371201,860848,892614.0,924629.0,Faisalabad,10-06-2021,View
27,Rs. 40000 Premium,17,370594,7870,211541,747096,NaN,NaN,Muzaffarabad,10-06-2021,View
28,Rs. 100,34,636604,221550,451785,506256,NaN,NaN,Multan,17-05-2021,View
29,Rs. 1500,86,602642,587960,925211,942100,NaN,NaN,Karachi,17-05-2021,View
30,Rs. 750,86,38012,831,314705,417508,NaN,NaN,Quetta,15-04-2021,View
31,Rs. 15000,86,476828,120835,524976,990472,NaN,NaN,Hyderabad,01-04-2021,View
32,Rs. 200,85,40529,249733,348312,691026,950368.0,982211.0,Faisalabad,15-03-2021,View
33,Rs. 25000 Premium,1,794905874214,333290,466253,787225,840925.0,851041.0,Multan,10-03-2021,View
34,Rs. 40000 Premium,16,12085,239849,758623,994854,NaN,NaN,Rawalpindi,10-03-2021,View
35,Rs. 100,33,124119,75899,104906,561989,NaN,NaN,Karachi,15-02-2021,View
36,Rs. 1500,85,414654,11149,39344,609775,NaN,NaN,Quetta,15-02-2021,View
37,Rs. 7500,85,773753,164860,323713,812741,NaN,NaN,Lahore,01-02-2021,View
38,Rs. 750,85,217739,194668,871860,953604,NaN,NaN,Hyderabad,15-01-2021,View
39,Rs. 15000,85,378251,497007,718384,811208,NaN,NaN,Muzaffarabad,04-01-2021,View
40,Rs. 200,84,699479,72451,282656,720562,991452.0,996251.0,Rawalpindi,15-12-2020,View
41,Rs. 40000 Premium,15,998029,213322,457930,805482,NaN,NaN,Hyderabad,10-12-2020,View
42,Rs. 1500,84,458090,21076,389925,909271,NaN,NaN,Quetta,16-11-2020,View
43,Rs. 100,32,466358,86187,248360,394957,NaN,NaN,Faisalabad,16-11-2020,View
44,Rs. 7500,84,193853,195676,448508,639512,NaN,NaN,Karachi,02-11-2020,View
45,Rs. 25000,35,185473,404002,651544,857590,NaN,NaN,Peshawar,02-11-2020,View
46,Rs. 750,84,854741,44848,168263,728072,NaN,NaN,Lahore,15-10-2020,View
47,Rs. 15000,84,515400,79719,370991,971907,NaN,NaN,Multan,01-10-2020,View
48,Rs. 200,83,96176,252176,615558,693713,745540.0,747752.0,Peshawar,15-09-2020,View
49,Rs. 40000 Premium,14,665868,169862,210732,625309,NaN,NaN,Rawalpindi,10-09-2020,View

In [7]:
# replace NaN with empty string
df = dfs.replace(np.nan, '')
df.head(50)

,Prize Bond,Draw No.,1st,2nd,2nd.1,2nd.2,2nd.3,2nd.4,City,Date,Full List
0,Rs. 750,91,722561,321896,828159,873486,,,Lahore,15-07-2022,View
1,Rs. 200,90,489317,482044,585014,678913,720703.0,770704.0,Multan,15-06-2022,View
2,Rs. 25000 Premium,6,415455857641,127995,464283,482643,484175.0,585235.0,Hyderabad,10-06-2022,View
3,Rs. 40000 Premium,21,763153,16018,318363,341290,,,Muzaffarabad,10-06-2022,View
4,Rs. 100,38,93241,109857,297539,479884,,,Faisalabad,16-05-2022,View
5,Rs. 1500,90,928756,68381,673933,924554,,,Rawalpindi,16-05-2022,View
6,Rs. 750,90,394635,207865,529894,829039,,,Karachi,15-04-2022,View
7,Rs. 200,89,793039,128737,390413,591489,705889.0,796069.0,Lahore,15-03-2022,View
8,Rs. 40000 Premium,20,755505,216179,311017,335736,,,Quetta,10-03-2022,View
9,Rs. 25000 Premium,5,96298193729,66227,284279,604401,696721.0,901103.0,Rawalpindi,10-03-2022,View
10,Rs. 100,37,904546,74566,259751,885455,,,Hyderabad,15-02-2022,View
11,Rs. 1500,89,878598,243545,457662,509633,,,Muzaffarabad,15-02-2022,View
12,Rs. 750,89,4208,511294,549996,983274,,,Peshawar,17-01-2022,View
13,Rs. 200,88,259580,380,233133,725485,871732.0,956938.0,Hyderabad,15-12-2021,View
14,Rs. 40000 Premium,19,953829,366951,599135,629631,,,Lahore,10-12-2021,View
15,Rs. 25000 Premium,4,16253067408,38203,171265,551833,655804.0,916353.0,Quetta,10-12-2021,View
16,Rs. 100,36,406160,50000,422885,619067,,,Peshawar,15-11-2021,View
17,Rs. 1500,88,708623,121234,251386,788311,,,Faisalabad,15-11-2021,View
18,Rs. 750,88,69845,172166,321134,828622,,,Rawalpindi,15-10-2021,View
19,Rs. 200,87,752824,368787,412125,437022,490233.0,759209.0,Muzaffarabad,15-09-2021,View
20,Rs. 25000 Premium,3,77928879917,17928,299043,366072,435276.0,924342.0,Hyderabad,10-09-2021,View
21,Rs. 40000 Premium,18,619284,11192,82571,460593,,,Peshawar,10-09-2021,View
22,Rs. 100,35,891043,212399,288254,660539,,,Faisalabad,16-08-2021,View
23,Rs. 1500,87,581729,91829,210953,759528,,,Multan,16-08-2021,View
24,Rs. 750,87,331809,232705,842723,908062,,,Lahore,15-07-2021,View
25,Rs. 200,86,514859,129441,268617,317693,423265.0,914859.0,Peshawar,15-06-2021,View
26,Rs. 25000 Premium,2,171790639589,100688,371201,860848,892614.0,924629.0,Faisalabad,10-06-2021,View
27,Rs. 40000 Premium,17,370594,7870,211541,747096,,,Muzaffarabad,10-06-2021,View
28,Rs. 100,34,636604,221550,451785,506256,,,Multan,17-05-2021,View
29,Rs. 1500,86,602642,587960,925211,942100,,,Karachi,17-05-2021,View
30,Rs. 750,86,38012,831,314705,417508,,,Quetta,15-04-2021,View
31,Rs. 15000,86,476828,120835,524976,990472,,,Hyderabad,01-04-2021,View
32,Rs. 200,85,40529,249733,348312,691026,950368.0,982211.0,Faisalabad,15-03-2021,View
33,Rs. 25000 Premium,1,794905874214,333290,466253,787225,840925.0,851041.0,Multan,10-03-2021,View
34,Rs. 40000 Premium,16,12085,239849,758623,994854,,,Rawalpindi,10-03-2021,View
35,Rs. 100,33,124119,75899,104906,561989,,,Karachi,15-02-2021,View
36,Rs. 1500,85,414654,11149,39344,609775,,,Quetta,15-02-2021,View
37,Rs. 7500,85,773753,164860,323713,812741,,,Lahore,01-02-2021,View
38,Rs. 750,85,217739,194668,871860,953604,,,Hyderabad,15-01-2021,View
39,Rs. 15000,85,378251,497007,718384,811208,,,Muzaffarabad,04-01-2021,View
40,Rs. 200,84,699479,72451,282656,720562,991452.0,996251.0,Rawalpindi,15-12-2020,View
41,Rs. 40000 Premium,15,998029,213322,457930,805482,,,Hyderabad,10-12-2020,View
42,Rs. 1500,84,458090,21076,389925,909271,,,Quetta,16-11-2020,View
43,Rs. 100,32,466358,86187,248360,394957,,,Faisalabad,16-11-2020,View
44,Rs. 7500,84,193853,195676,448508,639512,,,Karachi,02-11-2020,View
45,Rs. 25000,35,185473,404002,651544,857590,,,Peshawar,02-11-2020,View
46,Rs. 750,84,854741,44848,168263,728072,,,Lahore,15-10-2020,View
47,Rs. 15000,84,515400,79719,370991,971907,,,Multan,01-10-2020,View
48,Rs. 200,83,96176,252176,615558,693713,745540.0,747752.0,Peshawar,15-09-2020,View
49,Rs. 40000 Premium,14,665868,169862,210732,625309,,,Rawalpindi,10-09-2020,View

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Prize Bond  620 non-null    object
 1   Draw No.    620 non-null    int64
 2   1st         620 non-null    int64
 3   2nd         620 non-null    int64
 4   2nd.1       620 non-null    int64
 5   2nd.2       620 non-null    int64
 6   2nd.3       620 non-null    object
 7   2nd.4       620 non-null    object
 8   City        620 non-null    object
 9   Date        620 non-null    object
 10  Full List   620 non-null    object
dtypes: int64(5), object(6)
memory usage: 53.4+ KB

In [9]:
df.to_csv('prizeinfo.csv',          # Export pandas DataFrame as CSV
            header = True)